{
 "title": "HMCi - Power System Overview",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [ "Power" ],
 "time": {
  "from": "now-7d",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Processors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col ($tag_servername)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utlized" ], "type": "alias" }
      ],
      [
       { "params": [ "totalProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "availableProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ],
      [
       { "params": [ "configurableProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "configurable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": " $col ($tag_servername)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server_memory",
     "select": [
      [
       { "params": [ "assignedMemToLpars" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "assigned" ], "type": "alias" }
      ],
      [
       { "params": [ "availableMem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Processor Pools",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_poolname ($tag_servername)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "query": "SELECT mean(\"utilizedProcUnits\") AS \"utilized\" FROM \"server_sharedProcessorPool\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($interval), \"servername\", \"poolname\", \"pool\" fill(null)",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utilized" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Processor Pools",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_poolname ($tag_servername)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "query": "SELECT mean(\"utilizedProcUnits\") / mean(\"assignedProcUnits\") AS \"Utilization\" FROM \"server_sharedProcessorPool\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval), \"poolname\", \"servername\" fill(none)",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "System Processors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_servername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "query": "SELECT mean(\"utilizedProcUnits\") / mean(\"totalProcUnits\") AS \"Utilization\" FROM \"server_processor\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY \"servername\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Processor Pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col ($tag_servername)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server_physicalProcessorPool",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utlized" ], "type": "alias" }
      ],
      [
       { "params": [ "borrowedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "borrowed" ], "type": "alias" }
      ],
      [
       { "params": [ "configuredProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "configured" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Processor Pools",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_poolname ($tag_servername)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "select": [
      [
       { "params": [ "availableProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utlized" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Throughput - Transferred By VLAN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "vlan $tag_vlanId ($tag_servername)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "vlanId" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lpar_net_virtual",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Fiber Channel Adapters - Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_location ($tag_servername)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vios_storage_FC",
     "select": [
      [
       { "params": [ "transmittedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  }
 ]
}