# HMCi Configuration
# Copy this file into /etc/hmci.toml and customize to your environment.

# How often to query HMC's for data - in seconds
hmci.update = 30

# Rescan HMC's for new systems and partitions - every x update
hmci.rescan = 120

# InfluxDB to save metrics into
[influx]
url = "http://localhost:8086"
username = "root"
password = ""
database = "hmci"

# One or more HMC's to query for data and metrics
[hmc]

# HMC on our primary site
[hmc.site1]
url = "https://10.10.10.10:12443"
username = "hmci"
password = "hmcihmci"
unsafe = true   # Ignore SSL cert. errors


# Example
#[hmc.site2]
#url = "https://10.10.20.20:12443"
#username = "viewer"
#password = "someSecret"
#unsafe = false
