{
 "title": "IBM Power - HMCi - System Resources",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [ "Power" ],
 "time": {
  "from": "now-24h",
  "now": false,
  "to": "now-30s"
 },
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   }
  ]
 },
 "panels": [
  { "title": "Server - $ServerName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ServerName" },
  {
   "title": "Shared Processor Pools - Core Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_poolname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "query": "SELECT mean(\"utilizedProcUnits\") AS \"utilized\" FROM \"server_sharedProcessorPool\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($interval), \"servername\", \"poolname\", \"pool\" fill(null)",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utilized" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Processor Pools - Utilization Percentage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_poolname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "query": "SELECT (mean(\"utilizedProcUnits\") / mean(\"assignedProcUnits\")) * 100 AS \"Utilization\" FROM \"server_sharedProcessorPool\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval), \"poolname\" fill(null)",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Pool - Utilization Percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "query": "SELECT (mean(\"utilizedProcUnits\") / mean(\"availableProcUnits\")) * 100 AS \"Utilization\" FROM \"server_physicalProcessorPool\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Processor Pool  - Core Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_physicalProcessorPool",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utlized" ], "type": "alias" }
      ],
      [
       { "params": [ "borrowedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "borrowed" ], "type": "alias" }
      ],
      [
       { "params": [ "availableProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ],
      [
       { "params": [ "configuredProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "configured" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decmbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_memory",
     "select": [
      [
       { "params": [ "assignedMemToLpars" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "assigned" ], "type": "alias" }
      ],
      [
       { "params": [ "availableMem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Throughput - By VLAN",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "binBps", "label": "bytes" }
   ],
   "targets": [
    {
     "alias": "vlan $tag_vlanId - $col bytes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "vlanId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_net_virtual",
     "select": [
      [
       { "params": [ "receivedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "recv" ], "type": "alias" }
      ],
      [
       { "params": [ "sentBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *-1" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    },
    {
     "alias": "vlan $tag_vlanId - $col pkts",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "vlanId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_net_virtual",
     "query": "SELECT last(\"receivedPackets\") AS \"recv\", last(\"sentPackets\")  *-1 AS \"sent\" FROM \"lpar_net_virtual\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($interval), \"servername\", \"vlanId\" fill(null)",
     "select": [
      [
       { "params": [ "receivedPackets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "recv" ], "type": "alias" }
      ],
      [
       { "params": [ "sentPackets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *-1" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_FC",
     "select": [
      [
       { "params": [ "transmittedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "server_energy_thermal",
     "query": "SELECT mean(\"cpuTemperature*\") FROM \"server_energy_thermal\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval), \"system\", \"servername\" fill(linear)",
     "select": [
      [
       { "params": [ "cpuTemperature_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-1" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-2" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-3" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_servername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "server_energy_power",
     "select": [
      [
       { "params": [ "powerReading" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  }
 ]
}