{
 "title": "IBM Power - HMCi - Logical Partitions",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [ "Power" ],
 "time": {
  "from": "now-6h",
  "now": false,
  "to": "now-1m"
 },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server Name",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   },
   {
    "name": "LPAR",
    "label": "Logical Partition",
    "query": "SHOW TAG VALUES FROM \"lpar_processor\" WITH KEY = \"lparname\" WHERE servername =~ /$ServerName/"
   }
  ]
 },
 "panels": [
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LPAR Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_details",
     "query": "SELECT last(\"id\") AS \"ID\", \"osType\" AS \"OS\", \"state\" AS \"State\", \"affinityScore\" AS \"Affinity Score\" FROM \"lpar_details\" WHERE (\"servername\" =~ /^$ServerName$/) AND (\"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY \"lparname\"",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "type" ], "type": "field" }
      ],
      [
       { "params": [ "affinityScore" ], "type": "field" }
      ],
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "osType" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  {
   "title": "LPAR Processor",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_details",
     "query": "SELECT last(\"weight\") AS \"Weight\", last(\"entitledProcUnits\") AS \"Entitled\", last(\"currentVirtualProcessors\") AS \"VP\", (last(\"utilizedProcUnits\") / last(\"maxProcUnits\")) * 100 AS \"Utilization\",  last(\"mode\") AS \"Mode\" FROM \"lpar_processor\" WHERE (\"servername\" =~ /^$ServerName$/) AND (\"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY \"lparname\" fill(previous)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "type" ], "type": "field" }
      ],
      [
       { "params": [ "affinityScore" ], "type": "field" }
      ],
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "osType" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  { "title": "Storage I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Virtual Fiber Channel Adapters - Read Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_lparname read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_storage_vFC",
     "query": "SELECT mean(\"value\") FROM \"PartitionVirtualFiberChannelAdapters\" WHERE (\"system\" =~ /^$ManagedSystem$/ AND \"name\" != 'transmittedBytes' AND \"partition\" =~ /^$Partition$/) AND $timeFilter GROUP BY time($interval), \"wwpn\", \"partition\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "readBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters - Write Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_lparname write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_storage_vFC",
     "query": "SELECT mean(\"writeBytes\") FROM \"lpar_storage_vFC\" WHERE (\"servername\" =~ /^$ServerName$/ AND \"lparname\" =~ /^$LparName$/) AND $timeFilter GROUP BY time(1m), \"lparname\"",
     "select": [
      [
       { "params": [ "writeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Adapters",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "$tag_lparname - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_storage_virtual",
     "query": "SELECT mean(\"writeBytes\") FROM \"lpar_storage_virtual\" WHERE (\"servername\" =~ /^$ServerName$/ AND \"lparname\" =~ /^$LparName$/) AND $timeFilter GROUP BY time($interval), \"lparname\"",
     "select": [
      [
       { "params": [ "readBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "writeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  {
   "title": "Generic Adapters",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "$tag_lparname writeBytes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_storage_generic",
     "query": "SELECT mean(\"writeBytes\") FROM \"lpar_storage_virtual\" WHERE (\"servername\" =~ /^$ServerName$/ AND \"lparname\" =~ /^$LparName$/) AND $timeFilter GROUP BY time($interval), \"lparname\"",
     "select": [
      [
       { "params": [ "readBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "writeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Virtual Network Adapters - Received Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "$tag_lparname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_net_virtual",
     "select": [
      [
       { "params": [ "receivedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Network Adapters  - Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_lparname sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_net_virtual",
     "select": [
      [
       { "params": [ "sentBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Processor Units - Utilization Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_lparname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$ServerName$/",
     "query": "SELECT (last(\"utilizedProcUnits\") / last(\"maxProcUnits\")) * 100 AS \"usage\" FROM \"lpar_processor\" WHERE (\"servername\" =~ /^$ServerName$/ AND \"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY time($interval), \"lparname\", \"servername\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processor Units - Utilization Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_lparname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$ServerName$/",
     "query": "SELECT (last(\"utilizedProcUnits\") / last(\"maxProcUnits\")) * 100 AS \"usage\" FROM \"lpar_processor\" WHERE (\"servername\" =~ /^$ServerName$/ AND \"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY time($interval), \"lparname\", \"servername\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "NUMA Affinity Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_lparname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "lpar_details",
     "select": [
      [
       { "params": [ "affinityScore" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Assigned",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_lparname",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_memory",
     "select": [
      [
       { "params": [ "logicalMem" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  }
 ]
}