{
 "title": "IBM Power - HMCi - Virtual I/O Servers",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [
  "Power",
  "AIX",
  "VIOS"
 ],
 "time": {
  "from": "now-6h",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   },
   {
    "name": "ViosName",
    "label": "Virtual I/O Server",
    "query": "SHOW TAG VALUES FROM \"vios_details\" WITH KEY = \"viosname\" WHERE servername =~ /$ServerName/ AND time > now() - 24h"
   }
  ]
 },
 "panels": [
  {
   "title": "VIOS Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "viosname" ], "type": "tag" }
     ],
     "measurement": "vios_details",
     "query": "SELECT last(\"id\") AS \"id\", \"type\", \"osType\", \"state\", \"affinityScore\" FROM \"lpar_details\" WHERE (\"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY \"lparname\"",
     "select": [
      [
       { "params": [ "viosid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "viosstate" ], "type": "field" }
      ],
      [
       { "params": [ "affinityScore" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "VIOS Processor",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_details",
     "query": "SELECT last(\"weight\") AS \"Weight\", last(\"entitledProcUnits\") AS \"Entitled\", last(\"currentVirtualProcessors\") AS \"VP\", (last(\"utilizedProcUnits\") / last(\"maxProcUnits\")) * 100 AS \"Utilization\",  last(\"mode\") AS \"Mode\" FROM \"vios_processor\" WHERE (\"servername\" =~ /^$ServerName$/) AND (\"viosname\" =~ /^$ViosName$/) AND $timeFilter GROUP BY \"viosname\" fill(previous)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "type" ], "type": "field" }
      ],
      [
       { "params": [ "affinityScore" ], "type": "field" }
      ],
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "osType" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  {
   "title": " Memory - $ServerName - $ViosName",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_viosname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_memory",
     "select": [
      [
       { "params": [ "utilizedPct" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Processors - $ServerName - $ViosName",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_viosname - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_processor",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "utilized" ], "type": "alias" }
      ],
      [
       { "params": [ "donatedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "donated" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Fiber Channel Adapters - $ServerName - $ViosName - Read",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_viosname: $tag_id ($tag_location)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_FC",
     "select": [
      [
       { "params": [ "readBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Fiber Channel Adapters - $ServerName - $ViosName - Write",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_viosname: $tag_id ($tag_location",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_FC",
     "select": [
      [
       { "params": [ "writeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters - $ServerName - $ViosName - Read",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps", "label": "Read" }
   ],
   "targets": [
    {
     "alias": "$tag_viosname: $tag_id ($tag_location) read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_vFC",
     "select": [
      [
       { "params": [ "readBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters - $ServerName - $ViosName - Write",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps", "label": "Write" }
   ],
   "targets": [
    {
     "alias": "$tag_viosname: $tag_id ($tag_location) write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_vFC",
     "select": [
      [
       { "params": [ "writeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Storage - $ServerName - $ViosName",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_viosname - $tag_location",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_physical",
     "select": [
      [
       { "params": [ "transmittedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - $ServerName - $ViosName",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_viosname - $tag_location (shared)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_network_shared",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    },
    {
     "alias": "$tag_viosname - $tag_location (generic)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_network_generic",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    },
    {
     "alias": "$tag_viosname - $tag_location (virtual)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_network_virtual",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  }
 ]
}