{
 "title": "IBM Power - HMC Managed Systems - Energy",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [ "POWER" ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   }
  ]
 },
 "panels": [
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_servername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "server_energy_power",
     "select": [
      [
       { "params": [ "powerReading" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_servername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "server_energy_power",
     "select": [
      [
       { "params": [ "powerReading" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  { "title": "$ServerName Thermal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "ServerName" },
  {
   "title": "$ServerName - Inlet",
   "type": "stat",
   "description": "Inlet air temperature.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_servername - $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "server_energy_thermal",
     "select": [
      [
       { "params": [ "inletTemperature_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ServerName - CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "server_energy_thermal",
     "query": "SELECT mean(\"cpuTemperature*\") FROM \"server_energy_thermal\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval), \"system\", \"servername\" fill(linear)",
     "select": [
      [
       { "params": [ "cpuTemperature_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-1" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-2" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-3" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  }
 ]
}