{
 "title": "IBM Power - HMC Managed Systems - Virtual I/O Servers",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [
  "Power",
  "AIX",
  "VIOS"
 ],
 "time": {
  "from": "now-3h",
  "now": false,
  "to": "now-1m"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   },
   {
    "name": "ViosName",
    "label": "Virtual I/O Server",
    "query": "SHOW TAG VALUES FROM \"vios_details\" WITH KEY = \"viosname\" WHERE servername =~ /$ServerName/ AND time > now() - 24h"
   }
  ]
 },
 "panels": [
  {
   "title": "$ServerName - $ViosName Memory",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_vios",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_memory",
     "select": [
      [
       { "params": [ "utilizedPct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ServerName - $ViosName - Processors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_viosname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_processor",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ServerName - $ViosName -  Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_viosname: $tag_id ($tag_location)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_FC",
     "select": [
      [
       { "params": [ "transmittedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ServerName - $ViosName - Network",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_viosname - shared",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_network_shared",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    },
    {
     "alias": "$tag_viosname - generic",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_network_generic",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    },
    {
     "alias": "$tag_viosname - virtual",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_network_virtual",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  }
 ]
}