{
 "title": "IBM Power - HMC Managed Systems - Resources",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [ "Power" ],
 "time": {
  "from": "now-3h",
  "now": false,
  "to": "now"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ManagedSystem",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"SystemProcessor\" WITH KEY = \"system\" WHERE time > now() - 24h"
   },
   {
    "name": "Partition",
    "label": "Logical Partition",
    "query": "SHOW TAG VALUES FROM \"PartitionProcessor\" WITH KEY = \"partition\" WHERE system =~ /$ManagedSystem/"
   }
  ]
 },
 "panels": [
  { "title": "$ManagedSystem Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ManagedSystem" },
  {
   "title": "$ManagedSystem Shared Processor Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_pool $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemSharedProcessorPool",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/Units/" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem Processor Units",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Processor Units" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "name", "operator": "=~", "value": "/Units/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemMemory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem Processor Utilization",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "utilizedProcUnits" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  { "title": "$ManagedSystem Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "ManagedSystem" },
  {
   "title": "$ManagedSystem - Physical Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_device transmitted",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemFiberChannelAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "transmittedBytes" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem - Shared Adapters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemSharedAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "transferredBytes" }
     ]
    }
   ]
  },
  { "title": "$ManagedSystem By Partition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 }, "repeat": "ManagedSystem" },
  {
   "title": "$ManagedSystem Processor Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_partition Utilized Processor Units",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "utilizedProcUnits" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_partition Memory",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionMemory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "logicalMem" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  }
 ]
}