{
 "title": "IBM Power - HMCi - System Resources",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [ "Power" ],
 "time": {
  "from": "now-2d",
  "now": false,
  "to": "now-1m"
 },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   }
  ]
 },
 "panels": [
  { "title": "Server - $ServerName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ServerName" },
  {
   "title": "Shared Processor Pools",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_poolname - $col - ",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Utilized Proc. Units" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Units",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Processor Units" }
   ],
   "targets": [
    {
     "alias": "Utilized",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "availableProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    },
    {
     "alias": "Configurable",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "configurableProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "totalProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_FC",
     "select": [
      [
       { "params": [ "transmittedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - Partitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "VLAN-$tag_vlanId $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "vlanId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_net_virtual",
     "select": [
      [
       { "params": [ "receivedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "recv" ], "type": "alias" }
      ],
      [
       { "params": [ "sentBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *-1" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "server_energy_thermal",
     "query": "SELECT mean(\"cpuTemperature*\") FROM \"server_energy_thermal\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval), \"system\", \"servername\" fill(linear)",
     "select": [
      [
       { "params": [ "cpuTemperature_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-1" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-2" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-3" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_servername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "server_energy_power",
     "select": [
      [
       { "params": [ "powerReading" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  }
 ]
}