{
 "title": "IBM Power - HMCi - Virtual I/O Servers",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [
  "Power",
  "AIX",
  "VIOS"
 ],
 "time": {
  "from": "now-2d",
  "now": false,
  "to": "now-1m"
 },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   },
   {
    "name": "ViosName",
    "label": "Virtual I/O Server",
    "query": "SHOW TAG VALUES FROM \"vios_details\" WITH KEY = \"viosname\" WHERE servername =~ /$ServerName/ AND time > now() - 24h"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "viosname" ], "type": "tag" }
     ],
     "measurement": "vios_details",
     "query": "SELECT last(\"id\") AS \"id\", \"type\", \"osType\", \"state\", \"affinityScore\" FROM \"lpar_details\" WHERE (\"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY \"lparname\"",
     "select": [
      [
       { "params": [ "viosid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "viosstate" ], "type": "field" }
      ],
      [
       { "params": [ "affinityScore" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": " Memory - $ServerName - $ViosName",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_viosname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_memory",
     "select": [
      [
       { "params": [ "utilizedPct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Processors - $ServerName - $ViosName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_viosname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_processor",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Fiber Channel Adapters - $ServerName - $ViosName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_viosname: $tag_id ($tag_location) read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_FC",
     "select": [
      [
       { "params": [ "readBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    },
    {
     "alias": "$tag_viosname: $tag_id ($tag_location) write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_storage_FC",
     "select": [
      [
       { "params": [ "writeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - $ServerName - $ViosName",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_viosname - shared",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_network_shared",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    },
    {
     "alias": "$tag_viosname - generic",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_network_generic",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    },
    {
     "alias": "$tag_viosname - virtual",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vios_network_virtual",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  }
 ]
}