{
 "title": "IBM Power - HMC Managed Systems - Resources",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [ "Power" ],
 "time": {
  "from": "now-3h",
  "now": false,
  "to": "now-1m"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   },
   {
    "name": "LparName",
    "label": "Partition",
    "query": "SHOW TAG VALUES FROM \"lpar_processor\" WITH KEY = \"lparname\" WHERE servername =~ /$ServerName/"
   }
  ]
 },
 "panels": [
  { "title": "$ServerName Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ManagedSystem" },
  {
   "title": "Shared Processor Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_poolname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Units",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Processor Units" }
   ],
   "targets": [
    {
     "alias": "Utilized",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "availableProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    },
    {
     "alias": "Configurable",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "configurableProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "totalProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Utilization",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_processor",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ServerName Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "ManagedSystem",
   "collapsed": true,
   "panels": [
    {
     "title": "$ServerName - Physical Fiber Channel Adapters",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_location",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "location" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vios_storage_FC",
       "select": [
        [
         { "params": [ "transmittedBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
       ]
      }
     ]
    },
    {
     "title": "$ServerName - Shared Adapters",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_location",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "location" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vios_network_shared",
       "select": [
        [
         { "params": [ "transferredBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "$ServerName By Partition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "ManagedSystem" },
  {
   "title": "LPAR Processor Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_lparname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_processor",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "lparname", "operator": "=~", "value": "/^$LparName$/" }
     ]
    }
   ]
  },
  {
   "title": "LPAR Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_lparname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "lparname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lpar_memory",
     "select": [
      [
       { "params": [ "logicalMem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "lparname", "operator": "=~", "value": "/^$LparName$/" }
     ]
    }
   ]
  }
 ]
}