{
 "title": "IBM Power - HMC Managed Systems - Virtual I/O Servers",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [
  "Power",
  "AIX",
  "VIOS"
 ],
 "time": {
  "from": "now-3h",
  "now": false,
  "to": "now"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ManagedSystem",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"SystemProcessor\" WITH KEY = \"system\" WHERE time > now() - 24h"
   },
   {
    "name": "Vios",
    "label": "Virtual I/O Server",
    "query": "SHOW TAG VALUES FROM \"SystemFiberChannelAdapters\" WITH KEY = \"vios\" WHERE system =~ /$ManagedSystem/"
   }
  ]
 },
 "panels": [
  {
   "title": "$ManagedSystem - $Vios - Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_vios: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemViosMemory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "vios", "operator": "=~", "value": "/^$Vios$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/Mem/" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem - $Vios - Processors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_vios: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemViosProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "vios", "operator": "=~", "value": "/^$Vios$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/ProcUnits$/" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem - $Vios -  Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vios: $tag_id ($tag_device)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemFiberChannelAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "vios", "operator": "=~", "value": "/^$Vios$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "transmittedBytes" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem - $Vios - Virtual Ethernet Adapters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vios: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemVirtualEthernetAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "vios", "operator": "=~", "value": "/^$Vios$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/.*Bytes/" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem - $Vios - Shared Adapters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vios: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemSharedAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "vios", "operator": "=~", "value": "/^$Vios$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "transferredBytes" }
     ]
    }
   ]
  }
 ]
}