{
 "title": "IBM Power - HMC Managed Systems - Logical Partitions",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [ "Power" ],
 "time": {
  "from": "now-3h",
  "now": false,
  "to": "now-1m"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ManagedSystem",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"SystemProcessor\" WITH KEY = \"system\" WHERE time > now() - 24h"
   },
   {
    "name": "Partition",
    "label": "Logical Partition",
    "query": "SHOW TAG VALUES FROM \"PartitionProcessor\" WITH KEY = \"partition\" WHERE system =~ /$ManagedSystem/"
   }
  ]
 },
 "panels": [
  {
   "title": "Processor Units - Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "utilizedProcUnits" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Network Adapters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_partition - VLAN $tag_vlanId: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "vlanId" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionVirtualEthernetAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "!~", "value": "/Physical/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_wwpn : $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "wwpn" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionVirtualFiberChannelAdapters",
     "query": "SELECT mean(\"value\") FROM \"PartitionVirtualFiberChannelAdapters\" WHERE (\"system\" =~ /^$ManagedSystem$/ AND \"name\" != 'transmittedBytes' AND \"partition\" =~ /^$Partition$/) AND $timeFilter GROUP BY time($interval), \"wwpn\", \"partition\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "transmittedBytes" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  },
  {
   "title": "NUMA Affinity Score",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionAffinityScore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "affinityScore" }
     ]
    }
   ]
  }
 ]
}