{
 "title": "Power Systems - HMC Logical Partitions",
 "description": "HMC metrics from HMCi",
 "tags": [ "Power" ],
 "time": {
  "from": "now-3h",
  "now": false,
  "to": "now"
 },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ManagedSystem",
    "query": "SHOW TAG VALUES FROM \"SystemProcessor\" WITH KEY = \"system\""
   },
   {
    "name": "Partition",
    "query": "SHOW TAG VALUES FROM \"PartitionProcessor\" WITH KEY = \"partition\" where system =~ /$ManagedSystem/"
   }
  ]
 },
 "panels": [
  {
   "title": "Processors - Utilized",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "utilizedProcUnits" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Processors - Capped Utilized",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "utilizedCappedProcUnits" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Processors - Uncapped Utilized",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "utilizedUncappedProcUnits" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory - Logical",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionMemory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "logicalMem" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Network Adapter:  physical throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_partition viosid: $tag_viosId vlan $tag_vlanId: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "vlanId" ], "type": "tag" },
      { "params": [ "viosId" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionVirtualEthernetAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/PhysicalBytes/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Network Adapter:  virtual throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_partition vlan $tag_vlanId: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "vlanId" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionVirtualEthernetAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "!~", "value": "/Physical/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Partition Affinity Score",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_partition: AffinityScore",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionAffinityScore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "affinityScore" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_wwpn : $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "wwpn" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionVirtualFiberChannelAdapters",
     "query": "SELECT mean(\"value\") FROM \"PartitionVirtualFiberChannelAdapters\" WHERE (\"system\" =~ /^$ManagedSystem$/ AND \"name\" != 'transmittedBytes' AND \"partition\" =~ /^$Partition$/) AND $timeFilter GROUP BY time($interval), \"wwpn\", \"partition\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "transmittedBytes" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/time/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  }
 ]
}