{
 "title": "Power Systems - HMC Logical Partitions",
 "description": "HMC Logical Partitions",
 "tags": [ "AIX" ],
 "time": {
  "from": "now/w",
  "now": false,
  "to": "now"
 },
 "templating": {
  "list": [
   {
    "name": "ManagedSystem",
    "query": "SHOW TAG VALUES FROM \"SystemProcessor\" WITH KEY = \"system\""
   },
   {
    "name": "Partition",
    "query": "SHOW TAG VALUES FROM \"PartitionProcessor\" WITH KEY = \"partition\" where system =~ /$ManagedSystem/"
   }
  ]
 },
 "panels": [
  {
   "title": "Processors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "utilizedProcUnits" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Processors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/apped/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionProcessor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/time/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionMemory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Network Adapter:  physical throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_partition viosid: $tag_ViosID vlan $tag_VlanID: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "VlanID" ], "type": "tag" },
      { "params": [ "ViosID" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionVirtualEthernetAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/Bytes/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/PhysicalBytes/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Network Adapter:  virtual throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_partition vlan $tag_VlanID: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "VlanID" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionVirtualEthernetAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/Bytes/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/PhysicalBytes/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_wwpn : $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "wwpn" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionVirtualFiberChannelAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/Bytes/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/trans/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_partition $tag_wwpn : $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "wwpn" ], "type": "tag" },
      { "params": [ "partition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionVirtualFiberChannelAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "", "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/Bytes/" },
      { "condition": "AND", "key": "partition", "operator": "=~", "value": "/^$Partition$/" }
     ]
    }
   ]
  }
 ]
}