{
 "title": "Power Systems - HMC Virtual Input Output Servers",
 "description": "HMC metrics from HMCi",
 "tags": [
  "Power",
  "AIX"
 ],
 "time": {
  "from": "now-3h",
  "now": false,
  "to": "now"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ManagedSystem",
    "query": "SHOW TAG VALUES FROM \"SystemProcessor\" WITH KEY = \"system\""
   },
   {
    "name": "Vios",
    "label": "VIOS",
    "query": "SHOW TAG VALUES FROM \"SystemFiberChannelAdapters\" WITH KEY = \"vios\" where system =~ /$ManagedSystem/"
   }
  ]
 },
 "panels": [
  { "title": "$ManagedSystem Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ManagedSystem" },
  {
   "title": "$ManagedSystem VIOS Physical Fiber Channel Adapters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vios: $tag_id / $tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemFiberChannelAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "vios", "operator": "=~", "value": "/^$Vios$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "transmittedBytes" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem Shared Adapters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vios: $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemSharedAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "vios", "operator": "=~", "value": "/^$Vios$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "transferredBytes" }
     ]
    }
   ]
  },
  {
   "title": "$ManagedSystem VIOS  Generic Physical Adapters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vios: $tag_device xmit",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SystemGenericPhysicalAdapters",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$ManagedSystem$/" },
      { "condition": "AND", "key": "vios", "operator": "=~", "value": "/^$Vios$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "transmittedBytes" }
     ]
    }
   ]
  }
 ]
}