{
 "title": "HMCi - Power Partition Overview - Prometheus",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [
  "Prometheus",
  "VM",
  "IBM Power"
 ],
 "time": {
  "from": "now-7d",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System Name",
    "query": {
     "query": "label_values(system_processor_available_units,system)"
    }
   },
   {
    "name": "partition",
    "label": "Partition Name",
    "query": {
     "query": "label_values(partition_processor_entitled_units{system=~\"$system\"},partition)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Details",
       "groupBy": [
        { "params": [ "lparname" ], "type": "tag" }
       ],
       "measurement": "lpar_details",
       "query": "SELECT last(\"weight\") AS \"Weight\", last(\"mode\") AS \"Mode\", last(\"entitledProcUnits\") AS \"eCPU\",  mean(\"utilizedProcUnits\") / mean(\"entitledProcUnits\")*100 AS \"Utilization eCPU\", last(\"currentVirtualProcessors\") AS \"vCPU\", mean(\"utilizedProcUnits\") / mean(\"currentVirtualProcessors\") * 100 AS \"Utilization vCPU\"  FROM \"lpar_processor\" WHERE (\"servername\" =~ /^$ServerName$/) AND (\"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY \"lparname\" fill(previous)",
       "select": [
        [
         { "params": [ "id" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "id" ], "type": "alias" }
        ],
        [
         { "params": [ "type" ], "type": "field" }
        ],
        [
         { "params": [ "affinityScore" ], "type": "field" }
        ],
        [
         { "params": [ "state" ], "type": "field" }
        ],
        [
         { "params": [ "osType" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
       ]
      },
      {
       "alias": "Details",
       "query": "SELECT last(\"id\") AS \"ID\", last(\"state\") as \"State\", last(\"osType\") as \"OS Type\", last(\"affinityScore\") as \"Affinity Score\" FROM \"lpar_details\" WHERE (\"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY \"lparname\"  fill(previous)"
      }
     ]
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processor Units - Utilization Stacked",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_processor_utilized_units{partition=~\"$partition\", system=~\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processor Units - Utilization / Entitled Percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(partition) ((partition_processor_utilized_units{partition=~\"$partition\"}) / (partition_processor_entitled_units{partition=~\"$partition\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Network Adapters - Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_network_virtual_received_bytes{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual Network Adapters  - Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_network_virtual_sent_bytes{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SRIOV Network Adapters - Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_network_sriov_received_bytes{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SRIOV Network Adapters  - Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_network_sriov_sent_bytes{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters - Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_storage_vfc_read_bytes{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters - Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_storage_vfc_write_bytes{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual SCSI Adapters - Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_storage_generic_read_bytes{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual SCSI Adapters - Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_storage_generic_write_bytes{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NUMA Affinity Score",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_info_affinity_ratio{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Assigned - Stacked",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(partition) (partition_memory_logical_mb{system=~\"$system\", partition=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}