{
 "title": "HMCi - Power VIO Overview - Prometheus",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [
  "TODO",
  "Prometheus",
  "IBM Power",
  "Virtualized IO"
 ],
 "time": {
  "from": "now-7d",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System Name",
    "query": {
     "query": "label_values(system_info_utilized_proc_units,system)"
    }
   },
   {
    "name": "vios",
    "label": "Virtual I/O Server",
    "query": {
     "query": "label_values(vio_info_affinity_ratio{system=~\"$system\"},vios)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": " Memory - $system - $vios",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vio_memory_utilized_mb / vio_memory_assigned_mb",
     "legendFormat": "{{vios}}"
    }
   ]
  },
  {
   "title": "Processors - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "vio_processor_utilized_units  ", "legendFormat": "{{vios}}" }
   ]
  },
  {
   "title": "Network Sent - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "vio_network_sea_sent_bytes{system=~\"$system\", vios=~\"$vios\"}",
     "legendFormat": "{{vios}} {{location}}"
    }
   ]
  },
  {
   "title": "Network Received - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "vio_network_sea_received_bytes{system=~\"$system\", vios=~\"$vios\"}",
     "legendFormat": "{{vios}} {{location}}"
    }
   ]
  },
  {
   "title": "Fiber Channel Adapters - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "vio_storage_fc_transmitted_bytes{system=~\"$system\", vios=~\"$vios\"}",
     "legendFormat": "{{system}} {{location}}"
    }
   ]
  },
  {
   "title": "Physical Storage - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vio_storage_physical_transmitted_bytes{system=~\"$system\", vios=~\"$vios\"}",
     "legendFormat": "{{system}} {{location}}"
    }
   ]
  },
  {
   "title": "Virtual Adapters - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vio_storage_virtual_transmitted_bytes{system=~\"$system\", vios=~\"$vios\"}",
     "legendFormat": "{{system}} {{location}}"
    }
   ]
  }
 ]
}