{
 "title": "HMCi - Power LPAR Utilization",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "time": {
  "from": "now-6h",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server Name",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   },
   {
    "name": "LPAR",
    "label": "Logical Partition",
    "query": "SHOW TAG VALUES FROM \"lpar_processor\" WITH KEY = \"lparname\" WHERE servername =~ /$ServerName/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processor Units - Utilized / Max",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_lparname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$ServerName$/",
     "query": "SELECT mean(\"utilizedProcUnits\") / mean(\"currentVirtualProcessors\") AS \"usage\" FROM \"lpar_processor\" WHERE (\"servername\" =~ /^$ServerName$/ AND \"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY time($interval), \"lparname\", \"servername\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Virtual Network Adapters",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_servername - $tag_lparname ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lpar_net_virtual",
     "select": [
      [
       { "params": [ "receivedPhysicalBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "sentPhysicalBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" },
      { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_servername - $tag_lparname ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lparname" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lpar_storage_vFC",
     "query": "SELECT mean(\"value\") FROM \"PartitionVirtualFiberChannelAdapters\" WHERE (\"system\" =~ /^$ManagedSystem$/ AND \"name\" != 'transmittedBytes' AND \"partition\" =~ /^$Partition$/) AND $timeFilter GROUP BY time($interval), \"wwpn\", \"partition\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "readBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "writeBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  }
 ]
}