{
 "title": "HMCi - Power VIO Overview",
 "description": "https://bitbucket.org/mnellemann/hmci/",
 "tags": [
  "Power",
  "AIX",
  "VIOS"
 ],
 "time": {
  "from": "now-7d",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   },
   {
    "name": "ViosName",
    "label": "Virtual I/O Server",
    "query": "SHOW TAG VALUES FROM \"vios_details\" WITH KEY = \"viosname\" WHERE servername =~ /$ServerName/ AND time > now() - 24h"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information: [bitbucket.org/mnellemann/hmci](https://bitbucket.org/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "VIOS Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "viosname" ], "type": "tag" }
     ],
     "measurement": "vios_details",
     "query": "SELECT last(\"id\") AS \"id\", \"type\", \"osType\", \"state\", \"affinityScore\" FROM \"lpar_details\" WHERE (\"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY \"lparname\"",
     "select": [
      [
       { "params": [ "viosid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "viosstate" ], "type": "field" }
      ],
      [
       { "params": [ "affinityScore" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "VIOS Processor",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_details",
     "query": "SELECT last(\"weight\") AS \"Weight\", last(\"entitledProcUnits\") AS \"Entitled\", last(\"currentVirtualProcessors\") AS \"VP\", (last(\"utilizedProcUnits\") / last(\"maxProcUnits\")) * 100 AS \"Utilization\",  last(\"mode\") AS \"Mode\" FROM \"vios_processor\" WHERE (\"servername\" =~ /^$ServerName$/) AND (\"viosname\" =~ /^$ViosName$/) AND $timeFilter GROUP BY \"viosname\" fill(previous)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "type" ], "type": "field" }
      ],
      [
       { "params": [ "affinityScore" ], "type": "field" }
      ],
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "osType" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  {
   "title": " Memory - $ServerName - $ViosName",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_servername - $tag_viosname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vios_memory",
     "select": [
      [
       { "params": [ "utilizedPct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Processors - $ServerName - $ViosName",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_servername - $tag_viosname ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vios_processor",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utilized" ], "type": "alias" }
      ],
      [
       { "params": [ "donatedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "donated" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - $ServerName - $ViosName",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_servername - $tag_viosname - ($tag_location shared)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vios_network_shared",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    },
    {
     "alias": "$tag_servername - $tag_viosname - ($tag_location shared)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "vios_network_generic",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    },
    {
     "alias": "$tag_systemname - $tag_viosname - ($tag_location shared)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "systemname" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "vios_network_virtual",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Fiber Channel Adapters - $ServerName - $ViosName",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_servername - $tag_viosname - ($tag_id / $tag_location)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "vios_storage_FC",
     "select": [
      [
       { "params": [ "transmittedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Storage - $ServerName - $ViosName",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_servername - $tag_viosname ($tag_location)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "vios_storage_physical",
     "select": [
      [
       { "params": [ "transmittedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Adapters - $ServerName - $ViosName",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_servername - $tag_viosname - ($tag_id - $tag_location)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "viosname" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vios_storage_virtual",
     "select": [
      [
       { "params": [ "transmittedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" },
      { "condition": "AND", "key": "viosname", "operator": "=~", "value": "/^$ViosName$/" }
     ]
    }
   ]
  }
 ]
}