{
 "title": "HMCi - Power System Overview - InfluxDB",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [
  "Influx",
  "IBM Power",
  "Hardware"
 ],
 "time": {
  "from": "now-7d",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System Name",
    "query": {
     "query": "SHOW TAG VALUES FROM \"system_processor\" WITH KEY = \"system\" WHERE time > now() - 24h"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Processors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col ($tag_system)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_processor",
     "select": [
      [
       { "params": [ "utilized_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utlized" ], "type": "alias" }
      ],
      [
       { "params": [ "installed_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "available_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ],
      [
       { "params": [ "configurable_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "configurable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": " $col ($tag_servername)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_memory",
     "select": [
      [
       { "params": [ "assigned_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "assigned" ], "type": "alias" }
      ],
      [
       { "params": [ "available_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "System Processors Available",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_system",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_processor",
     "select": [
      [
       { "params": [ "available_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "System Memory Available",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_system",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_memory",
     "select": [
      [
       { "params": [ "available_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Processor Pools",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_pool ($tag_system)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "query": "SELECT mean(\"utilized_units\") / mean(\"assigned_units\") AS \"Utilization\" FROM \"system_shared_processor_pool\" WHERE (\"system\" =~ /^$system$/) AND $timeFilter GROUP BY time($__interval), \"pool\", \"system\" fill(none)",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "System Processors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "poolname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_sharedProcessorPool",
     "query": "SELECT mean(\"utilized_units\") / mean(\"installed_units\") AS \"Utilization\" FROM \"system_processor\" WHERE (\"system\" =~ /^$system$/) AND $timeFilter GROUP BY \"system\", time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "utilizedProcUnits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Processor Pools - Utilization Cores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_pool ($tag_system)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "pool::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_shared_processor_pool",
     "query": "SELECT mean(\"utilizedProcUnits\") AS \"utilized\" FROM \"server_sharedProcessorPool\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($interval), \"servername\", \"poolname\", \"pool\" fill(null)",
     "select": [
      [
       { "params": [ "utilized_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utilized" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Processor Pools - Utilization Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_pool ($tag_system)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_shared_processor_pool",
     "query": "SELECT  mean(\"utilized_units\") / mean(\"available_units\") AS \"available\" FROM \"system_shared_processor_pool\" WHERE (\"system\"::tag =~ /^$system$/) AND $timeFilter GROUP BY time($interval), \"pool\"::tag, \"system\"::tag fill(none)",
     "select": [
      [
       { "params": [ "available_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Processor Pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col ($tag_system)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_physical_processor_pool",
     "select": [
      [
       { "params": [ "utilized_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utlized" ], "type": "alias" }
      ],
      [
       { "params": [ "borrowed_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "borrowed" ], "type": "alias" }
      ],
      [
       { "params": [ "configured_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "configured" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Fiber Channel Adapters - Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_location ($tag_system) $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vio_storage_fc",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Throughput - VLAN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "vlan-$tag_vlan ($tag_system) $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "vlan::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "partition_network_virtual",
     "select": [
      [
       { "params": [ "received_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "rx" ], "type": "alias" }
      ],
      [
       { "params": [ "sent_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Throughput - SR-IOV Ports",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_location ($tag_system) $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_network_sriov",
     "select": [
      [
       { "params": [ "received_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rx" ], "type": "alias" }
      ],
      [
       { "params": [ "sent_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  }
 ]
}