{
 "title": "HMCi - Power System Utilization - Prometheus",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [
  "IBM Power",
  "Hardware",
  "Prometheus"
 ],
 "time": {
  "from": "now-7d",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processors - Utilized / Configurable",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "system_processor_utilized_units / system_processor_configurable_units   ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processors - Utilized / Configurable",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_processor_utilized_units / system_processor_configurable_units",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Processors - Utilized / Configurable",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_processor_utilized_units / system_processor_configurable_units",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Processors - Configurable / Installed",
   "type": "bargauge",
   "description": "Configurable processors are activated and available for use and assignment. The difference up to the total is \"dark cores\" which can be activated by code or used with PEP-2.0.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_processor_configurable_units / system_processor_installed_units",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Memory Utilization - Assigned / Installed",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_assigned_mb / system_memory_installed_mb",
     "legendFormat": "{{system}}"
    }
   ]
  }
 ]
}