{
 "title": "HMCi - Power System Energy - InfluxDB",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [
  "Influx",
  "IBM Power",
  "Thermal",
  "Power"
 ],
 "time": { "from": "now-7d", "to": "now-30s" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System Name",
    "query": {
     "query": "SHOW TAG VALUES FROM \"system_energy\" WITH KEY = \"system\" WHERE time > now() - 24h"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  { "title": "$system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "ServerName" },
  {
   "title": "Power Consumption - $system",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system_energy",
     "select": [
      [
       { "params": [ "power_watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperatures - $system",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col $system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_thermal",
     "query": "SELECT mean(\"cpuTemperature*\") FROM \"server_energy_thermal\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval), \"system\", \"servername\" fill(linear)",
     "select": [
      [
       { "params": [ "cpu_1_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU-1" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_proc0_core0_0_temp_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Proc-0" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperatures - $system",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$system $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system_thermal",
     "query": "SELECT mean(\"cpuTemperature*\") FROM \"server_energy_thermal\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval), \"system\", \"servername\" fill(linear)",
     "select": [
      [
       { "params": [ "cpu_1_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-1" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_proc0_core0_0_temp_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Proc-0" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Inlet Temperatures - $system",
   "type": "stat",
   "description": "Inlet air temperature.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$system $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_thermal",
     "select": [
      [
       { "params": [ "inlet_1_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "inlet1" ], "type": "alias" }
      ],
      [
       { "params": [ "inlet_Ambient_0_Temp_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "ambient" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Inlet Temperatures - $system",
   "type": "timeseries",
   "description": "Inlet air temperature.",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$system $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_thermal",
     "select": [
      [
       { "params": [ "inlet_1_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Inlet 1" ], "type": "alias" }
      ],
      [
       { "params": [ "inlet_Ambient_0_Temp_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ambient 0" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  }
 ]
}