{
 "title": "HMCi - Power System Energy",
 "description": "https://git.data.coop/nellemann/hmci",
 "tags": [ "Power" ],
 "time": { "from": "now-7d", "to": "now-30s" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ServerName",
    "query": "SHOW TAG VALUES FROM \"server_processor\" WITH KEY = \"servername\" WHERE time > now() - 24h"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information: [https://git.data.coop/nellemann/hmci](https://git.data.coop/nellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_servername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server_energy_power",
     "select": [
      [
       { "params": [ "powerReading" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ServerName - CPU Temperature",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_energy_thermal",
     "query": "SELECT mean(\"cpuTemperature*\") FROM \"server_energy_thermal\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval), \"system\", \"servername\" fill(linear)",
     "select": [
      [
       { "params": [ "cpuTemperature_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU-1" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU-2" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU-3" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU-4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ServerName - CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "server_energy_thermal",
     "query": "SELECT mean(\"cpuTemperature*\") FROM \"server_energy_thermal\" WHERE (\"servername\" =~ /^$ServerName$/) AND $timeFilter GROUP BY time($__interval), \"system\", \"servername\" fill(linear)",
     "select": [
      [
       { "params": [ "cpuTemperature_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-1" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-2" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-3" ], "type": "alias" }
      ],
      [
       { "params": [ "cpuTemperature_4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU-4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ServerName - Inlet Temperature",
   "type": "stat",
   "description": "Inlet air temperature.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_energy_thermal",
     "select": [
      [
       { "params": [ "inletTemperature_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "inlet1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "$ServerName - Inlet Temperature",
   "type": "timeseries",
   "description": "Inlet air temperature.",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server_energy_thermal",
     "select": [
      [
       { "params": [ "inletTemperature_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Inlet 1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$ServerName$/" }
     ]
    }
   ]
  }
 ]
}