{
 "title": "HMCi - Power VIO Overview - InfluxDB",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [
  "Influx",
  "IBM Power",
  "Virtualized IO"
 ],
 "time": {
  "from": "now-7d",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System Name",
    "query": {
     "query": "SHOW TAG VALUES FROM \"system_processor\" WITH KEY = \"system\" WHERE time > now() - 24h"
    }
   },
   {
    "name": "vios",
    "label": "Virtual I/O Server",
    "query": {
     "query": "SHOW TAG VALUES FROM \"vio_info\" WITH KEY = \"vios\" WHERE system =~ /$system/ AND time > now() - 24h"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "VIOS Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "vios::tag" ], "type": "tag" }
     ],
     "measurement": "vio_info",
     "query": "SELECT last(\"id\") AS \"id\", \"type\", \"osType\", \"state\", \"affinityScore\" FROM \"lpar_details\" WHERE (\"lparname\" =~ /^$LPAR$/) AND $timeFilter GROUP BY \"lparname\"",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "affinity_ratio" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vios::tag", "operator": "=~", "value": "/^$vios$/" }
     ]
    }
   ]
  },
  {
   "title": "VIOS Processor",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_details",
     "query": "SELECT last(\"weight\") AS \"Weight\", last(\"entitled_units\") AS \"Entitled\", last(\"vp_units\") AS \"VP\", (mean(\"utilized_units\") / mean(\"entitled_units\")) * 100 AS \"Utilization\",  last(\"mode\") AS \"Mode\" FROM \"vio_processor\" WHERE (\"system\" =~ /^$system$/) AND (\"vios\" =~ /^$vios$/) AND $timeFilter GROUP BY \"vios\" fill(previous)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "type" ], "type": "field" }
      ],
      [
       { "params": [ "affinityScore" ], "type": "field" }
      ],
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "osType" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    }
   ]
  },
  {
   "title": " Memory - $system - $vios",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_system - $tag_vios",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vio_memory",
     "query": "SELECT mean(\"utilized_mb\") / mean(\"assigned_mb\") FROM \"vio_memory\" WHERE (\"system\"::tag =~ /^$system$/ AND \"vios\"::tag =~ /^$vios$/) AND $timeFilter GROUP BY time($interval), \"vios\"::tag, \"system\"::tag fill(none)",
     "select": [
      [
       { "params": [ "utilized_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "vios::tag", "operator": "=~", "value": "/^$vios$/" }
     ]
    }
   ]
  },
  {
   "title": "Processors - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_vios ($col)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vio_processor",
     "select": [
      [
       { "params": [ "utilized_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "utilized" ], "type": "alias" }
      ],
      [
       { "params": [ "donated_units" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "donated" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "vios::tag", "operator": "=~", "value": "/^$vios$/" }
     ]
    }
   ]
  },
  {
   "title": "Network SEA - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_vios - ($tag_location) $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios::tag" ], "type": "tag" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vio_network_sea",
     "select": [
      [
       { "params": [ "received_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "RX" ], "type": "alias" }
      ],
      [
       { "params": [ "sent_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "TX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "vios::tag", "operator": "=~", "value": "/^$vios$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Virtual - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_vios - ($tag_location) $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios::tag" ], "type": "tag" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vio_network_virtual",
     "select": [
      [
       { "params": [ "received_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "RX" ], "type": "alias" }
      ],
      [
       { "params": [ "sent_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "TX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "vios::tag", "operator": "=~", "value": "/^$vios$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Generic - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_vios - ($tag_location) $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios::tag" ], "type": "tag" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vio_network_generic",
     "select": [
      [
       { "params": [ "received_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "RX" ], "type": "alias" }
      ],
      [
       { "params": [ "sent_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "TX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "vios::tag", "operator": "=~", "value": "/^$vios$/" }
     ]
    }
   ]
  },
  {
   "title": "Fiber Channel Adapters - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_vios - ($tag_location) $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios::tag" ], "type": "tag" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "vio_storage_fc",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "vios::tag", "operator": "=~", "value": "/^$vios$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Storage - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_vios ($tag_location) $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "vio_storage_physical",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "vios::tag", "operator": "=~", "value": "/^$vios$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Adapters - $system - $vios",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_system - $tag_vios - ( $tag_location) $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vios::tag" ], "type": "tag" },
      { "params": [ "location::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vio_storage_virtual",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "vios::tag", "operator": "=~", "value": "/^$vios$/" }
     ]
    }
   ]
  }
 ]
}