{
 "title": "HMCi - Power Partition Overview - InfluxDB",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [
  "Influx",
  "VM",
  "IBM Power"
 ],
 "time": {
  "from": "now-7d",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System Name",
    "query": {
     "query": "SHOW TAG VALUES FROM \"system_processor\" WITH KEY = \"system\" WHERE time > now() - 24h"
    }
   },
   {
    "name": "partition",
    "label": "Partition Name",
    "query": {
     "query": "SHOW TAG VALUES FROM \"partition_processor\" WITH KEY = \"partition\" WHERE system =~ /$system/ "
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Details",
     "groupBy": [
      { "params": [ "lparname" ], "type": "tag" }
     ],
     "measurement": "lpar_details",
     "query": "SELECT last(\"weight\") AS \"Weight\", last(\"mode\") AS \"Mode\", last(\"entitled_units\") AS \"eCPU\",  mean(\"utilized_units\") / mean(\"entitled_units\")*100 AS \"Utilization eCPU\", last(\"vp_units\") AS \"vCPU\", mean(\"utilized_units\") / mean(\"vp_units\") * 100 AS \"Utilization vCPU\"  FROM \"partition_processor\" WHERE (\"system\" =~ /^$system$/) AND (\"partition\" =~ /^$partition/) AND $timeFilter GROUP BY \"partition\" fill(previous)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "type" ], "type": "field" }
      ],
      [
       { "params": [ "affinityScore" ], "type": "field" }
      ],
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "osType" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "lparname", "operator": "=~", "value": "/^$LPAR$/" }
     ]
    },
    {
     "alias": "Details",
     "query": "SELECT last(\"id\") AS \"ID\", last(\"state\") as \"State\", last(\"type\") as \"OS Type\", last(\"affinity_ratio\") as \"Affinity Score\" FROM \"partition_info\" WHERE (\"partition\" =~ /^$partition$/) AND $timeFilter GROUP BY \"partition\"  fill(previous)"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processor Units - Utilization Stacked",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$ServerName$/",
     "query": "SELECT mean(\"utilized_units\") AS \"usage\" FROM \"partition_processor\" WHERE (\"partition\" =~ /^$partition$/ AND \"system\" =~ /^$system$/) AND $timeFilter GROUP BY time($interval), \"partition\", \"system\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processor Units - Utilization / Entitled",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$ServerName$/",
     "query": "SELECT (mean(\"utilized_units\") / mean(\"entitled_units\")) * 100 AS \"usage\" FROM \"partition_processor\" WHERE (\"system\" =~ /^$system$/ AND \"partition\" =~ /^$partition$/) AND $timeFilter GROUP BY time($interval), \"partition\", \"system\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Network Adapters (SEA) - Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "partition_network_virtual",
     "select": [
      [
       { "params": [ "received_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" },
      { "condition": "AND", "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Network Adapters (SEA)  - Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "partition_network_virtual",
     "select": [
      [
       { "params": [ "sent_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" },
      { "condition": "AND", "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "SRIOV Network Adapters - Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "partition_network_sriov",
     "select": [
      [
       { "params": [ "received_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" },
      { "condition": "AND", "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "SRIOV Network Adapters  - Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "partition_network_sriov",
     "select": [
      [
       { "params": [ "sent_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" },
      { "condition": "AND", "key": "system::tag", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters - Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" }
     ],
     "measurement": "partition_storage_vfc",
     "query": "SELECT mean(\"value\") FROM \"PartitionVirtualFiberChannelAdapters\" WHERE (\"system\" =~ /^$ManagedSystem$/ AND \"name\" != 'transmittedBytes' AND \"partition\" =~ /^$Partition$/) AND $timeFilter GROUP BY time($interval), \"wwpn\", \"partition\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Fiber Channel Adapters - Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "system::tag" ], "type": "tag" }
     ],
     "measurement": "partition_storage_vfc",
     "query": "SELECT mean(\"value\") FROM \"PartitionVirtualFiberChannelAdapters\" WHERE (\"system\" =~ /^$ManagedSystem$/ AND \"name\" != 'transmittedBytes' AND \"partition\" =~ /^$Partition$/) AND $timeFilter GROUP BY time($interval), \"wwpn\", \"partition\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NUMA Affinity Score",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "partition_info",
     "select": [
      [
       { "params": [ "affinity_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Assigned - Stacked",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_partition",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "partition::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "partition_memory",
     "select": [
      [
       { "params": [ "logical_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system::tag", "operator": "=~", "value": "/^$system$/" },
      { "condition": "AND", "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  }
 ]
}