{
 "title": "HMCi - Power System Energy - Prometheus",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [
  "Prometheus",
  "IBM Power",
  "Thermal",
  "Power"
 ],
 "time": { "from": "now-7d", "to": "now-30s" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "system", "label": "System Name", "query": { "query": "label_values(system)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  { "title": "$system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "ServerName" },
  {
   "title": "Power Consumption",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(system) (system_energy_power_watts{job=\"hmci\", system=~\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by(system) (system_energy_power_watts{job=\"hmci\", system=~\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$system - CPU Temperature",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(system) (system_thermal_cpu_1_celsius{system=~\"$system\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(system) (system_thermal_cpu_proc0_core0_0_temp_celsius{system=~\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$system - CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(system) (system_thermal_cpu_1_celsius{system=~\"$system\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(system) (system_thermal_cpu_proc0_core0_0_temp_celsius{system=~\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$system - Inlet Temperature",
   "type": "stat",
   "description": "Inlet air temperature.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(system) (system_thermal_inlet_1_celsius{system=~\"$system\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(system) (system_thermal_inlet_Ambient_0_Temp_celsius{system=~\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$system - Inlet Temperature",
   "type": "timeseries",
   "description": "Inlet air temperature.",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(system) (system_thermal_inlet_1_celsius{system=~\"$system\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(system) (system_thermal_inlet_Ambient_0_Temp_celsius{system=~\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}