{
 "title": "HMCi - Power System Overview - Prometheus",
 "description": "https://github.com/mnellemann/hmci/ - Metrics from IBM Power Systems",
 "tags": [
  "Prometheus",
  "IBM Power",
  "Hardware"
 ],
 "time": {
  "from": "now-7d",
  "now": false,
  "to": "now-30s"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System Name",
    "query": {
     "query": "label_values(system_processor_installed_units,system)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics collected from IBM Power HMC\n    \nFor more information visit: [github.com/mnellemann/hmci](https://github.com/mnellemann/hmci)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Processor Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(system) ((system_processor_utilized_units{system=~\"$system\"}) / (system_processor_configurable_units{system=~\"$system\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Processors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(system) (system_processor_installed_units{system=~\"$system\"})",
     "legendFormat": "{{system}} Installed"
    },
    {
     "expr": "avg by(system) (system_processor_configurable_units{system=~\"$system\"})",
     "legendFormat": "{{system}} Configurable"
    },
    {
     "expr": "avg by(system) (system_processor_available_units{system=~\"$system\"})",
     "legendFormat": "{{system}} Available"
    },
    {
     "expr": "avg by(system) (system_processor_utilized_units{system=~\"$system\"})",
     "legendFormat": "{{system}} Utilized"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(system) (system_memory_installed_mb{system=~\"$system\"})",
     "legendFormat": "{{system}} Installed"
    },
    {
     "expr": "avg by(system) (system_memory_assigned_mb{system=~\"$system\"})",
     "legendFormat": "{{system}} Assigned"
    },
    {
     "expr": "avg by(system) (system_memory_configurable_mb{system=~\"$system\"})",
     "legendFormat": "{{system}} Configurable"
    },
    {
     "expr": "avg by(system) (system_memory_available_mb{system=~\"$system\"})",
     "legendFormat": "{{system}} Available"
    }
   ]
  },
  {
   "title": "Shared Processor Pools",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(pool, system) (system_shared_processor_pool_utilized_units{system=~\"$system\"})",
     "legendFormat": "{{system}} {{pool}}"
    }
   ]
  },
  {
   "title": "Shared Processor Pools Percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(pool,system) ((system_shared_processor_pool_utilized_units{system=~\"$system\"}) / (system_shared_processor_pool_assigned_units{system=~\"$system\"}) * 100)",
     "legendFormat": "{{pool}} {{system}}"
    }
   ]
  },
  {
   "title": "System Processors Percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(system) ((system_processor_utilized_units{system=~\"$system\"}) / (system_processor_configurable_units{system=~\"$system\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Physical Processor Pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(system) (system_physical_processor_pool_utilized_units{system=~\"$system\"})",
     "legendFormat": "{{system}} utilized"
    },
    {
     "expr": "avg by(system) (system_physical_processor_pool_borrowed_units{system=~\"$system\"})",
     "legendFormat": "{{system}} borrowed"
    },
    {
     "expr": "avg by(system) (system_physical_processor_pool_available_units{system=~\"$system\"})",
     "legendFormat": "{{system}} borrowed"
    }
   ]
  },
  {
   "title": "Shared Processor Pools",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(pool, system) (system_shared_processor_pool_utilized_units{system=~\"$system\"})",
     "legendFormat": "{{system}} {{pool}}"
    }
   ]
  }
 ]
}